import { apiClient } from "../api/client";

// lib/services/resume.service.ts
export interface Resume {
  _id: string;
  user: string;
  title: string;
  isDefault: boolean;
  personalInfo: {
    firstName: string;
    lastName: string;
    email: string;
    phone?: string;
    location?: string;
    website?: string;
    linkedin?: string;
    github?: string;
    summary?: string;
    title?: string;
  };
  experience: Array<{
    _id?: string;
    company: string;
    position: string;
    location?: string;
    startDate: string;
    endDate?: string;
    current: boolean;
    description?: string;
    achievements?: string[];
  }>;
  education: Array<{
    _id?: string;
    institution: string;
    degree: string;
    fieldOfStudy?: string;
    location?: string;
    startDate: string;
    endDate?: string;
    current: boolean;
    description?: string;
    gpa?: number;
  }>;
  skills: Array<{
    _id?: string;
    name: string;
    level?: "beginner" | "intermediate" | "advanced" | "expert";
    category?: string;
  }>;
  certifications: Array<{
    _id?: string;
    name: string;
    issuer: string;
    date: string;
    expiryDate?: string;
    credentialId?: string;
    url?: string;
  }>;
  languages: Array<{
    _id?: string;
    name: string;
    proficiency: "basic" | "conversational" | "professional" | "native";
  }>;
  projects: Array<{
    _id?: string;
    name: string;
    description?: string;
    url?: string;
    technologies?: string[];
    startDate?: string;
    endDate?: string;
  }>;
  customSections: Array<{
    _id?: string;
    title: string;
    content: string;
    order: number;
  }>;
  pdfFile: {
    filename: string;
    mimeType: "application/pdf";
    path: string;
    size: number;
    uploadedAt: string;
  };
  template: "modern" | "classic" | "minimal" | "creative";
  visibility: "private" | "public" | "shared";
  status: "draft" | "active" | "archived";
  createdAt: string;
  updatedAt: string;
}

export interface AnalysisResult {
  score: number;
  strengths: string[];
  weaknesses: string[];
  suggestions: string[];
  recommendedJobs: string[];
}

export interface PersonalInfo {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  location?: string;
  website?: string;
  linkedin?: string;
  github?: string;
  summary?: string;
  title?: string;
}

// Structured content generated by the AI assistant for a resume
export interface GeneratedResumeContent {
  summary?: string;
  experiences?: Array<{
    company?: string;
    position?: string;
    description?: string;
    achievements?: string[];
  }>;
  skills?: string[];
  education?: Array<{
    institution?: string;
    degree?: string;
    fieldOfStudy?: string;
  }>;
  [key: string]: unknown;
}

export const resumeService = {
  async getMyResumes(): Promise<Resume[]> {
    const response = await apiClient.get("/resumes");
    return response.data.data?.resumes || [];
  },

  // Get all resumes with optional status filter
  async getResumes(params?: { status?: string }): Promise<Resume[]> {
    const queryParams = new URLSearchParams();
    if (params?.status) queryParams.append("status", params.status);
    const response = await apiClient.get(`/resumes?${queryParams.toString()}`);
    return response.data.data?.resumes || [];
  },

  // ✅ Get a single resume by ID
  async getResumeById(id: string): Promise<Resume> {
    const response = await apiClient.get(`/resumes/${id}`);
    return response.data.data;
  },

  // Get a single resume (alias)
  async getResume(id: string): Promise<Resume> {
    return this.getResumeById(id);
  },

  // ✅ Create a new resume
  async createResume(data: Partial<Resume>): Promise<Resume> {
    const response = await apiClient.post("/resumes", data);
    return response.data.data;
  },

  // ✅ Update personal info
  async updatePersonalInfo(id: string, data: Partial<PersonalInfo>): Promise<Resume> {
    const response = await apiClient.put(`/resumes/${id}/personal-info`, data);
    return response.data.data;
  },

  // ✅ Update summary
  async updateSummary(id: string, summary: string): Promise<Resume> {
    const response = await apiClient.put(`/resumes/${id}/summary`, { summary });
    return response.data.data;
  },

  // Update a resume
  async updateResume(id: string, data: Partial<Resume>): Promise<Resume> {
    const response = await apiClient.put(`/resumes/${id}`, data);
    return response.data.data;
  },

  // ✅ Delete a resume
  async deleteResume(id: string): Promise<{ success: boolean }> {
    const response = await apiClient.delete(`/resumes/${id}`);
    return response.data;
  },

  // Set default resume
  async setDefaultResume(id: string): Promise<Resume> {
    const response = await apiClient.put(`/resumes/${id}/default`);
    return response.data.data;
  },

  // ✅ Analyze resume
  async analyzeResume(id: string): Promise<{ analysis: AnalysisResult }> {
    const response = await apiClient.get(`/resumes/${id}/analyze`);
    return response.data.data;
  },

  // ✅ Generate AI cover letter
  async generateCoverLetter(resumeId: string, jobId: string): Promise<{ coverLetter: string }> {
    const response = await apiClient.post(`/resumes/${resumeId}/generate-cover-letter`, { jobId });
    return response.data.data;
  },

  // ✅ Generate AI summary
  async generateAISummary(resumeId: string): Promise<{ summary: string }> {
    const response = await apiClient.post(`/resumes/${resumeId}/generate-summary`);
    return response.data.data;
  },

  // Generate AI content for resume
  // Returns the backend ApiResponse payload (access generated content via `.data`)
  async generateContent(data: {
    jobTitle?: string;
    experience?: string;
  }): Promise<{ data: GeneratedResumeContent }> {
    const response = await apiClient.post("/resumes/generate-content", data);
    return response.data;
  },

  // Get PDF preview URL
  async getPDFPreviewUrl(resumeId: string): Promise<string> {
    try {
      const response = await apiClient.get(`/resumes/${resumeId}/pdf`, {
        responseType: "blob",
      });
      const blob = new Blob([response.data], { type: "application/pdf" });
      return URL.createObjectURL(blob);
    } catch (error) {
      console.error("PDF preview error:", error);
      throw error;
    }
  },

  // Download PDF
  async downloadPDF(resumeId: string): Promise<void> {
    try {
      const response = await apiClient.get(`/resumes/${resumeId}/pdf`, {
        responseType: "blob",
      });
      const url = window.URL.createObjectURL(
        new Blob([response.data], { type: "application/pdf" }),
      );
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", "resume.pdf");
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("PDF download error:", error);
      throw error;
    }
  },
};
